### PR TITLE
views: hide missed table when empty

### PR DESCRIPTION
**Pull request by SeaLightHouse**
Hide 'No missed votes in this block'

This resolves issue #472

### CODE REVIEW

**Comment by chappjc** [comment]
Thanks for the PR!

A general suggestion with UI related PRs: show before and after screenshots.

**Comment by SeaLightHouse** [comment]
OK , I will do that from next time .
Thanks

**Comment by SeaLightHouse** [comment]
ok

**Comment by chappjc** [comment]
Please also rename the PR to be descriptive of the change. e.g. "views: hide missed table when empty"

**Pull request merged**
