### PR TITLE
Make ticketpool chart all time zoom button default

### PR DESCRIPTION
**Pull request by dmigwi**
Set "All Time" as the default Zoom button then ticketpool chart

### CODE REVIEW

**Comment by dmigwi** [comment]
https://github.com/decred/dcrdata/issues/993

**Comment by chappjc** [comment]
I'm not sure if this has anything to do with this PR, but I seem to occasionally get a hang with the spinning update graphic.  Looking at the console I see this:

image

@buck54321 What do you thing this might be related to?

**Comment by dmigwi** [comment]
I haven't encountered such a case scenario but my initial analysis, show that some part payload expected for the price graph might be missing at those specific instances.
Possible cause being that the queries for the above chart take too long than expected. If I may ask, Can you be able to replicate the error above since I haven't seen such on my end? Do that bug happen when your system is under heavy load?

**Comment by chappjc** [comment]
I can replicate it just by refreshing a few times.  webpack all fresh and browser hard-refreshed.

**Comment by chappjc** [comment]
I found two bugs with the ticketpool js controller when looking into the unrelated issue.  Proposed fixes.: https://github.com/decred/dcrdata/pull/1003

**Pull request merged**
