### PR TITLE
js/controllers: remove unused const binance

### PR DESCRIPTION
**Pull request by chappjc**

### CODE REVIEW

**Comment by njirap** [comment]
Hi @chappjc 

On grepping 'binance' I find it hard coded in the same file maybe it's the variable you are removing that was supposed to be used at https://github.com/decred/dcrdata/blob/master/public/js/controllers/market_controller.js#L585

**Comment by buck54321** [comment]
That is what I intended, @njirap. Looks like I just hard-coded it on accident. Not sure why I didn't see the linter message.

**Comment by chappjc** [comment]
@buck54321 So you'd prefer to keep and use the `const`?  Seemed like extra code weight.

**Comment by buck54321** [comment]
Let's drop the `const` then.

**Pull request merged**
