### PR TITLE
show mining fees on the block page

### PR DESCRIPTION
**Pull request by McEdward**
screenshot 112

### CODE REVIEW

**Comment by McEdward** [comment]
Resolving issue #650

**Comment by chappjc** [comment]
How is "BLOCK MINING FEE" intended to differ from "TOTAL FEES COLLECTED"?

**Comment by McEdward** [comment]
> How is "BLOCK MINING FEE" intended to differ from "TOTAL FEES COLLECTED"?

TOTAL FEES COLLECTED is just the addition of all the transaction fees, not including the block mining fee

**Comment by McEdward** [comment]
I was wondering what name is preferable mining fee / total fees collected / miners fee / miner fees collected? @raedah @xaur

**Comment by McEdward** [comment]
screenshot 113

**Comment by xaur** [comment]
"Miner fees" or "Miner fees collected" sounds right. Just make sure to not remove "Miner(s)" from there.

**Comment by chappjc** [comment]
I'd like either Mining Fees or Miner Fees.  @raedah, preference?

**Comment by raedah** [comment]
Transaction Fees

**Pull request merged**
