### PR TITLE
Integrated Staking Reward Calculator feature

### PR DESCRIPTION
**Pull request by thanhnp2k**
Integrated Staking Reward Calculator feature allows estimating income achieved from DCR staking with input parameters Amount, StartDate and EndDate (indicating range).

Default parameters:
Amount: 1000 DCR
StartDate: 3 months ago
EndDate: Now
It is a feature based on the Pdanalytics underlying platform. And you can refer to the demo at the following link
http://tr2.localto.net:44759/

Screenshot
menu
default
edit input
amount error
daterange error 1
daterange errro 2

### CODE REVIEW

**Comment by ukane-philemon** [comment]
Hi @thanhnp2k, thanks for your effort. #1772 has an open PR already see: https://github.com/decred/dcrdata/pull/1949.

**Comment by xaur** [comment]
@thanhnp2k thanks for this PR and your interest in Decred! Please be aware that dcrdata is not actively developed these days (as you can see from #1949 linked above, it did not get a response since December 2022). I recommend talking to project maintainers before investing time to avoid wasted work.

You can reach the devs in #dcrdata chat in Matrix (see [how to join](https://docs.decred.org/getting-started/joining-matrix-channels/), email is optional). In case you don't get any luck with dcrdata, Decred has many other projects in active development (Go, Dart+Flutter, web). Feel free to ask for directions in the #dev chat ("DCR Development"). While Matrix account is not strictly required for contributing to Decred projects, it would be easier to sync with the other devs and discover things.

If creating a Matrix account is not an option, feel free to create an issue [here](https://github.com/decredcommunity/issues/issues) and I will answer your questions.

**Comment by xaur** [comment]
I forgot, we also have [Discord](https://discord.gg/dXSmwvYury) and [Reddit](https://www.reddit.com/r/decred/new/) for talk and questions.

**Comment by thanhnp2k** [comment]
> Hi @thanhnp2k, thanks for your effort. #1772 has an open PR already see: #1949.

I'm sorry. I saw your PR but I would be remiss in ignoring the principle of contributing to the project which is to confirm more clearly.
Your PR is still open from 2022, which makes me mistakenly think it is not completely approved and develop it in another direction.
I will pay more attention in future contributions

**Comment by thanhnp2k** [comment]
> I forgot, we also have [Discord](https://discord.gg/dXSmwvYury) and [Reddit](https://www.reddit.com/r/decred/new/) for talk and questions.

**Comment by chappjc** [comment]
https://github.com/decred/dcrdata/pull/1783 and https://github.com/decred/dcrdata/pull/1949 and https://matrix.to/#/!MWVGfiOSyEeQvegadG:decred.org/$D_rH-PU3_djk6gn-8k4bcrVjzgwMesuuCyUFuWpzE7c?via=decred.org&via=matrix.org&via=zettaport.com (chat) have clarified this issue.  Should be no backend computation.

**Pull request closed without merging**
