### PR TITLE
fix chart zoom for uninitialized charts

### PR DESCRIPTION
**Pull request by buck54321**
bug in address.js cause the loading animation to hang when chart isn't initialized

### CODE REVIEW

**Comment by chappjc** [comment]
Thanks for the PR.  Could you please squash and rebase the branch?

**Comment by buck54321** [comment]
I think I corrected it, but I'm not certain.

**Comment by chappjc** [comment]
Yup, that did it, thanks!

**Comment by buck54321** [comment]
Oh. I think I messed this up. This was for https://github.com/decred/dcrdata/issues/758.

**Pull request merged**
