### PR TITLE
Agenda chart data: inline -> AJAX

### PR DESCRIPTION
**Pull request by buck54321**
Removes inline chart data from agenda.tmpl. Data is retrieved via AJAX instead.

#843

### CODE REVIEW

**Comment by chappjc** [comment]
Looks nice.  Ready for testing?

**Comment by buck54321** [comment]
Yep. Test away.

**Comment by chappjc** [comment]
tACK.

Sorry, @buck54321, but you and gozart drew straws and his scss PR goes first, making your life a bit harder.  The index.js moved to the root of public, and there were css changes, so there will be conflicts.  But seriously, the bigger scss PR would be a pain to rebase I think.

**Comment by buck54321** [comment]
No problem. I was anticipating that. Better to make the structural changes first.

**Comment by chappjc** [comment]
Ready for that rebase now.

**Pull request merged**
