### PR TITLE
multi: devops

### PR DESCRIPTION
**Pull request by githubsands**
1. 'Dockerfile' is created, but a container/image still needs to be pushed on decred/dcrdata 
2. Add the ability to pull using docker in 'run_tests.sh'

### CODE REVIEW

**Comment by chappjc** [comment]
I think to get rid of the merge commits you'll have to git reset b59f8e89, git add (everything), git commit, force push.
Or whatever seems right.  Maybe back up first though.  :)

**Comment by chappjc** [comment]
Thanks for fixing that up @githubsands.  Could you offer a brief description of what goes on in run_tests.sh in terms of docker and what exactly it does (improvements?).  Thanks!

@decred/dcrdata Anyone experienced with docker wanna lend their eyes for a review?

**Comment by chappjc** [comment]
@dajohi Could you scan through this if you have a minute?

**Comment by orthomind** [comment]
To get these tests to run, I think you need to at least modify the .travis.yml file to load docker.  See, for example:

https://github.com/decred/dcrweb/blob/master/.travis.yml

You can then also have travis build the image itself before running the tests.  However, looking at the script, it's not clear to me that getting travis to build the image first will work with the way the script has been written here with the cache.

**Comment by orthomind** [comment]
Also, I'm thinking that maybe you shouldn't use the same Dockerfile for tests as for running the production service.  Tests require certain things in the image that aren't required for a production run (or, at least, I assume so!).

If we have separate Dockerfile's for each of testing and production, then production can use a multistage Dockerfile to keep it as small as possible.

I think we should also always build the testing image as part of the travis test process, rather than pulling it, so that the testing Dockerfile also gets tested each time.  If we rely on a pull, then it could be that changes to the Dockerfile that are part of that pull request would have caused tests to fail, but the tests didn't fail because the tests ran against the Dockerfile that's in the image registry rather than the new image that's requested to be merged (or vice versa: tests fail that wouldn't fail with the new proposed Dockerfile).

If I'm not making sense, let me know.

**Comment by chappjc** [comment]
Thank you both very much for your work on this.  This PR is now superseded by PR https://github.com/decred/dcrdata/pull/497/files

**Pull request closed without merging**
