### PR TITLE
gov/agendas: do not use compiled ConcensusDeployments

### PR DESCRIPTION
**Pull request by chappjc**
This eliminates the use of `chaincfg.Params.ConsensusDeployments` for determining the range of valid stake versions.  There is no reason to have this be compile time information when it can be figured out via `getvoteinfo`:

```
[DBG] AGDB: Stake version 4: [sdiffalgorithm lnsupport]
[DBG] AGDB: Stake version 5: [lnfeatures]
[DBG] AGDB: Stake version 6: [fixlnseqlocks]
[DBG] AGDB: Stake version 7: [headercommitments]
```

This also fixes a few bugs:
- In the agendas_controller, `Meter.drawIndicator`, and thus `ProgressMeter.draw` were broken because `Meter` was trying to reference `super`.
- The agendas table was in no particular order.  It is now ordered by vote version, then ID.
- Agenda votes in the defined state (yet to begin voting) threw JS errors from cumulativeVoteChoicesData and voteChoicesByBlockData.
- The same defined agendas showed NaN% in the legends, which is confusing.  It says zero now.

The titles of the agendas and proposals pages are renamed:
- Decred Vote Agendas Page => Consensus Deployment Agendas
- Decred Vote Proposals Page => Politeia Proposals
The word "Page" is silly since you're viewing it in a web browser.

The agendas page now:

image

### CODE REVIEW

**Comment by chappjc** [comment]
The meters agendas controller / meters error:

image

**Comment by chappjc** [comment]
Agendas controller error resolved in https://github.com/decred/dcrdata/pull/1586/commits/18b1b866ca38ad9d2915f01c46b22778232f298f.  `Meter.drawIndicator`, and thus `ProgressMeter.draw` were broken because `Meter` was trying to reference `super`.

**Comment by chappjc** [comment]
Pre-vote progress meters now look correct:

image

**Comment by buck54321** [comment]
Related: #1376

**Comment by chappjc** [comment]
Deployed for testing on https://alpha.dcrdata.org/agendas

**Comment by chappjc** [comment]
Been working on alpha, and (backported) on one of the main 5.1 backends.  Merging and deploying to the rest of the main backends.

**Pull request merged**
