### PR TITLE
upgrade exchange api versions

### LINKED ISSUE #1810: upgrade exchange API versions
```
https://api.binance.com/api/v1 -> v3
https://bittrex.com/api/v1.1 and v2.0 -> https://api.bittrex.com/v3
```

### PR DESCRIPTION
**Pull request by ukane-philemon**
https://api.coindesk.com/v1  -> v2
https://api.binance.com/api/v1 -> v3

Closes #1810

### CODE REVIEW

**Comment by chappjc** [comment]
Thanks!  No difference with these endpoints?
Can you comment on the 1000->5000 data point change?

**Comment by ukane-philemon** [comment]
Thanks for reviewing, there are no difference to these endpoint. Changes in binance v3 include new endpoints and removal of old endpoints not currently used by decred.
Change in limit
1000- previous max limit
5000- new max limit
Increasing  max limit allow endpoint to get ALL  current DCRBTC bids in binance order book.

**Comment by chappjc** [comment]
Sounds good.  Will test it out.  Interestingly, the v1 endpoint already seems happy to return more than a thousand data points (presently about 1700 asks), but that's probably because they upgraded a common component at some point and it shouldn't be allowing it.  Anyway, thanks again.

**Comment by ukane-philemon** [comment]
@chappjc Thanks for the feedback.

**Review by chappjc — APPROVED** [review]

**Pull request merged**
