### PR TITLE
Insight API - Misc cleanup [1], [2], [5], [5.1], [8], [8.1], [8.2], [9.1], [9.2], [9.3], [9.4]

### PR DESCRIPTION
**Pull request by papacarp**
These endpoints are ready for test and merge:

Full comparison list is here:  https://docs.google.com/spreadsheets/d/1WGHezqRG5VY-t4O6cGpZGwsq69IKJ3deEnERaVvQOb4

**[1] Block**

*Comparison*
image

*Example Output*
```
[
    {
        "hash": "000000000000000663a4ea037091a5ce844051f0c6d5fd0d0389103b993fc977",
        "confirmations": 11083,
        "size": 4154,
        "height": 235615,
        "version": 5,
        "merkleroot": "6c360aa257d7485326c1b5e9cad32d9d0f0a28dfa1654cbec3bff04a37bf033a",
        "tx": [
            "d1414ca25a008dfd6502b64ec77fa625b1f95f73828c975453920993ba4bf044",
            "24e3367c225234bda3b4fbe2279e446c39febbf5311bbfbef68a581bf168c6f0",
            "d2c249b66b73ed7942f476fb5d5977aadb0ff7c0da59ffc4529f6887a7845b3d",
            "1bef2b097b3d81dba57fee9e852df13f7f0fc729fcb772cfabc67c6ce3777413",
            "15be0712c0344db0e838f3f098125c0c11d67b6f6ca604995998a48f9dd6a67f",
            "a7524910d4abdae398f07d2ccfee102ac58f4a5647fc762c2e682c18829d4cc2",
            "354c967c3ee9f7aed979bc7eff1c05b56285057e4cc0be988fe4ab4f3630d39a",
            "66c9059b91f649c84b4a23a924e3e69aa69a6d1f5e4c4cf93750692a52274428",
            "ead3f793c8261b1498d0e3db53f5bb8961d4e4162dc2e2b9a88ad3bd166567a5",
            "95c0f5500f0fd853bddffe4e2d36d1c0df4f472936b0542b65f73c73f269c35f",
            "7199976fdf8871cb1a04e588bc25a2373740a6d8d004e725e85845e716b5618e"
        ],
        "time": 1525406423,
        "nonce": 881740634,
        "bits": "190ce566",
        "difficulty": 333039126.108207,
        "previousblockhash": "00000000000000013888138b5ba974ece595f20a8873a53bc533fb00bf056840",
        "nextblockhash": "000000000000000bb6708673b63bd6c3f4d0ad631b9b0a91cef33bc7c9051442",
        "reward": 21.37392543,
        "isMainChain": true
    }
]
```

**[2] Block Index**

```
{
    "blockHash": "0000000000000000817be0e4473f99be251518e3762957f731d077d5b274b847"
}
```

**[5] [5.1] Blocks (queryparams version shown for brevity)**
*Comparison*
image

*Example Output*

```
{
    "blocks": [
        {
            "height": 126949,
            "size": 2801,
            "hash": "00000000000000b9b2724a8af60fda67a3b72910f2a0d6ee290ff31e534c4175",
            "diff": 0,
            "sdiff": 0,
            "time": 1492905537,
            "txlength": 7
        },
        {
            "height": 126948,
            "size": 6650,
            "hash": "0000000000000234d31499770066344da85deaec3c057cd4d0849c91da237a1c",
            "diff": 0,
            "sdiff": 0,
            "time": 1492905288,
            "txlength": 17
        },
        {
            "height": 126947,
            "size": 5197,
            "hash": "00000000000001867a3aed194f59e383d9b1a161fa507f678dc473c7d30154f2",
            "diff": 0,
            "sdiff": 0,
            "time": 1492904835,
            "txlength": 18
        }
    ],
    "length": 3,
    "pagination": {
        "next": "2017-04-23",
        "prev": "2017-04-21",
        "currentTs": 1492905599,
        "current": "2017-04-22",
        "isToday": false,
        "more": true,
        "moreTs": 1492904835
    }
}
```

**[8] [8.1] Addr**

also implemented are from/to and noTxList query params (note appearances is misspelled on bitpay.insight..  gotta be compatible)

*Comparison*

image

*Example Output*

```
{
    "addrStr": "DshRLMBrqyDmMpp9gcz3bLgCnjMa75mrHsS",
    "balance": 0,
    "balanceSat": 0,
    "totalReceived": 93.00360718,
    "totalReceivedSat": 9300360718,
    "totalSent": 93.00360718,
    "totalSentSat": 9300360718,
    "unconfirmedBalance": 0,
    "unconfirmedBalanceSat": 0,
    "unconfirmedTxApperances": 0,
    "txApperances": 2,
    "transactions": [
        "08f0944772cd2fb292ed9907471a3acc33a659ec567baa6f621ab485e5fd82c9",
        "5d95f88528a1303c016ba10e26495d0e83cd6a3b8ff5239676b7cec03486d7cc"
    ]
}
```

**[9.1] [9.2] [9.3] [9.4] Addr values**

balance, totalReceived, totalSent, unconfirmedBalance

*Example Output*

```
208770778628
```

### CODE REVIEW

**Comment by chappjc** [comment]
Please rebase and resolve, thanks.  I want to get the Insight stuff in so we can branch cleanly for `2.1`, then @dmigwi's PR https://github.com/decred/dcrdata/pull/463 and then the more disruptive https://github.com/decred/dcrdata/pull/427 can follow. @dmigwi:  sorry for holding up your PRs, they are bigger changes.

**Comment by papacarp** [comment]
@chappjc this is ready for review

**Comment by chappjc** [comment]
Please allow edits from maintainers.  I wanted to review a part of this PR by way of edits this time.

**Comment by chappjc** [comment]
Nevermind my last comment.  I opened a PR on your branch with my edits:  https://github.com/papacarp/dcrdata/pull/1

**Comment by papacarp** [comment]
Changes incorporated and re-tested.  Ready to go.

**Pull request merged**
