### PR TITLE
refine hamburger menu style & animation

### PR DESCRIPTION
**Pull request by gozart1**
This addresses menu toggle alignment raised in https://github.com/decred/dcrdata/issues/423 and refines styling to match the design spec.

screen shot 2018-04-29 at 3 31 21 am

screen shot 2018-04-29 at 3 00 44 am
screen shot 2018-04-29 at 3 00 55 am

### CODE REVIEW

**Comment by raedah** [comment]
tested, works great.

**Comment by chappjc** [comment]
@raedah That space looks intentional, or at least it seems right.  Note that the right edge of the menu button is aligned with the right side of the Output table.

**Comment by chappjc** [comment]
Please rebase.  The new parameters link just needs to land in the menu.  BTW, if you check the box to allow edits from maintainer, I should be able to resolve this stuff.

**Comment by raedah** [comment]
To be more specific, the spacing is correct, but i expect the search bar (blue underline) to extend equally on the left and right side so that it includes the area shown in the red box.

**Comment by chappjc** [comment]
Ah.  I see now.
@gozart1, would this change and the rebase be something you could hit up today or tomorrow?  Otherwise, it's totally cool for me to handle it, if you permit edits from maintainers

**Comment by gozart1** [comment]
Oh its np, I'll fix it up now. I was also considering adding that off-menu click to close menu interaction, so we can wrap up https://github.com/decred/dcrdata/issues/423 ( close hotkey makes more sense as a separate PR focused on keyboard navigation comprehensively )

**Comment by gozart1** [comment]
- rebased with latest master
- has balanced search input padding
- has off menu click close handler

**Comment by chappjc** [comment]
tACK

**Pull request merged**
