### PR TITLE
Fix bugs in 3.0 version

### PR DESCRIPTION
**Pull request by dmigwi**
This PR blends the night mode colors with the nexthome page color and fixes a bug with explorertable due to the extra "Ticket Price Window" column added.

screenshot from 2018-10-26 22-35-09

#765 #764

### CODE REVIEW

**Comment by dmigwi** [comment]
I have changed the title so that it can reflect the extra bug fix that I have added here.

**Comment by dmigwi** [comment]
Another bug. Addresses chart x-axis value is not visible in night mode.

**Before**
screenshot from 2018-10-27 02-14-51

**After**
screenshot from 2018-10-27 02-23-40

**Comment by dmigwi** [comment]
This PR fixes the following bugs in version 3.0:
- Fixes the /nexthome night mode view including the common title bar to all pages.
- Makes the x-axis value on addresses charts and Agenda votes charts visible during night mode.
- Fixes a bug in the query fetching the oldest transaction timestamp for the addresses charts.
- Fixes a bug in the query fetching the agenda votes by height chart data.

**Comment by chappjc** [comment]
Each fix verified.  Nice work, thanks!

**Pull request merged**
