### PR TITLE
proposals: show voter turnout as percentage

### LINKED ISSUE #1392: proposals list: show voter turnout percentage
Currently https://alpha.dcrdata.org/proposals shows absolute vote counts. That number is interesting and must be shown somewhere, but in this table I think 30% would be more interesting than 12369 (for the DEX spec proposal).

### PR DESCRIPTION
**Pull request by njirap**
Resolves #1392

Screen Shot 2019-08-10 at 1 42 55 PM

### CODE REVIEW

**Comment by njirap** [comment]
`0` comes as `NaN% turnout` Looking into it

**Comment by njirap** [comment]
It's `NaN` because `NumOfEligibleVotes` = `0`

**Comment by njirap** [comment]
`NaN` fixed to `0`

Screen Shot 2019-08-10 at 2 16 20 PM

**Comment by njirap** [comment]
Removed whitespace before `%`
Screen Shot 2019-08-10 at 2 24 55 PM

**Comment by chappjc** [comment]
Now there's whitespace after the "(".  I think you'll have to sacrifice nice template code formatting for desired effect.

**Comment by chappjc** [comment]
Actually, you can do stuff like `{{-- if eq $v.NumOfEligibleVotes 0}}` to consume white space prior.

**Comment by njirap** [comment]
Whitespace is not stripped from the `0` because it is not in braces `{{}}`

Screen Shot 2019-08-11 at 5 40 29 PM

**Comment by chappjc** [comment]
`-}}` works too.
https://golang.org/pkg/text/template/#hdr-Text_and_spaces

**Comment by njirap** [comment]
Whitespace stripped from `0`
Screen Shot 2019-08-12 at 1 37 56 PM

**Pull request merged**
