### PR TITLE
multi: use txrules & txsizes.

### PR DESCRIPTION
**Pull request by dnldd**
This removes copied funcs and variables from `txsizes` and `txrules` packages in favour of using the packages instead now that [txsizes is no longer an internal package](https://github.com/decred/dcrwallet/pull/1573).

### CODE REVIEW

**Comment by njirap** [comment]
hallo.

Please advise how to fix the error I get from the change made to `go.sum` by this PR

```go: decred.org/cspp@v0.2.0: unrecognized import path "decred.org/cspp" (https fetch: Get https://decred.org/cspp?go-get=1: x509: certificate signed by unknown authority)
go: error loading module requirements```

**Comment by dnldd** [comment]
Looks like a tls issue fetching the cspp dependency.

**Comment by chappjc** [comment]
The decred.org ssl certificate looks ok on my end.   And chance you have some overzealous antivirus software on your machine @njirap.

**Comment by njirap** [comment]
No @chappjc . But also I've changed dev environments to another machine so I'm good now.

**Pull request merged**
