### PR TITLE
Account for front & backend timezone offsets when computing age

### PR DESCRIPTION
**Pull request by gozart1**
* fix negative numbers showing instead of age when timezone offfsets misalign 
(Builds upon https://github.com/decred/dcrdata/pull/927)

### CODE REVIEW

**Comment by ZeroASIC** [comment]
I'm just testing it a little bit and it looks like it works.  I did notice that the Address page has a column `Time UTC` but in this case should be `Time (CST)` or the appropriate timezone, which is how the homepage works.  I think line 221 of extras.tmpl needs to be updated from:
`<th>Time UTC</th>`
To:
`<th>Time ({{timezone}})</th>`

**Comment by chappjc** [comment]
Note that we can also change the postgresql data type. Presently it is just `timestamp`, which does not include a time zone by default, but this could be made into `timestamptz` (alias for `timestamp with time zone`).

And we can redefine the `String` method of `TimeDef` to include the timestamp: https://play.golang.org/p/_LJPzm_D0it

```go
package main

import (
	"fmt"
	"time"
)

type TimeDef struct {
	T time.Time
}

func (t TimeDef) String() string {
	return t.T.Format("2006-01-02 15:04:05 -0700 MST")
}

func main() {
	t := TimeDef{T: time.Now()}
	fmt.Printf("Right now it is %v", t)
}
```

Which outputs `Right now it is 2009-11-10 23:00:00 +0000 UTC`

**Comment by ZeroASIC** [comment]
Including the timezone in TimeDef was one of my suggestions in #927 as a better long term fix.  I was trying to fix the negative times without making fundamental changes to the timestamps.  Updating TimeDef and forcing the Unix timestamps into UTC might be a good idea.

**Comment by ZeroASIC** [comment]
Yes it does.
`var thisDate = new Date('2009-11-10 23:00:00 +0000 UTC');
console.log(thisDate);`

That prints out a valid time string to the console.
https://jsfiddle.net/d6p4kc9q/

**Comment by ZeroASIC** [comment]
> Yes it does.
> `var thisDate = new Date('2009-11-10 23:00:00 +0000 UTC');`
> `console.log(thisDate);`
> 
> That prints out a valid time string to the console.
> https://jsfiddle.net/d6p4kc9q/1/
> or an alert
> https://jsfiddle.net/d6p4kc9q/

Since that only works in Chrome, maybe the library gozart1 mentioned in the other PR would help.  https://momentjs.com/timezone/

**Comment by gozart1** [comment]
I don't like including the offsets in the time values themselves since that creates repetition of information and we should minimize that to preserve precious screen real estate. 

Although one thing to consider is if we should rewrite the date to local time in js enabled situations. 

There's endless ways we can deal with handling time. So letting the non-js experience guide us seems like a good tie breaker.

**Comment by gozart1** [comment]
If we did go with including timezone in the value, then the ideal format would be [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), ideally the flavor that matches https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString output

**Comment by ZeroASIC** [comment]
As long as we update `humanize.formatTxDate(stamp, withTimezone)` to return the correct format, then it shouldn't matter too much how it's handled.  I'll always vote for less data being passed from the server to the client instead of more.

**Pull request merged**
